root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ./apps/cmd/server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "ent", "migrations", "logs"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  log = "build-errors.log"
  stop_on_error = true

[log]
  time = true
